dataproc:
  project_id: "airy-task-454216-m7"
  region: "us-central1"
  cluster_name: "astra-dataproc-cluster"
  bucket: "rc_pai_batch_scripts"
  output_path: "gs://rc_pai_batch_scripts/output/fixed_statement_202406.txt"
  secure_bundle: "gs://rc_pai_batch_scripts/secure-connect-database_name.zip"
  keyspace: "card_statement"
  table: "fixed_statement_202406"
  main_script: "gs://rc_pai_batch_scripts/dataproc_astra_job.py"
