name: Deploy Dataproc Astra DB Job

on:
  push:
    branches:
      - main

jobs:
  dataproc-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set Up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'

    # - name: Install Dependencies
    #   run: |
    #     python3 -m pip install --upgrade pip
    #     pip3 install -r dataproc/requirements.txt

    - name: Authenticate to Google Cloud
      env:
        GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
        GCS_SERVICE_ACCOUNT_KEY: ${{ secrets.GCS_SERVICE_ACCOUNT_KEY }}
      run: |
        printf "%s" "${GCS_SERVICE_ACCOUNT_KEY}" > gcloud-service-key.json
        gcloud auth activate-service-account --key-file=gcloud-service-key.json
        gcloud config set project "$GCP_PROJECT"
        rm -f gcloud-service-key.json  # Clean up the key file

    - name: List Directories
      run: |
        echo "Listing all subfolders and files after GCP authentication:"
        ls -R

    - name: Upload Files to GCS
      env:
        GCS_BUCKET: ${{ secrets.GCS_BUCKET }}
      run: |
        gsutil -m rsync -r dataproc gs://$GCS_BUCKET/dataproc

    - name: Build Docker Image from GCS
      run: |
        gcloud builds submit gs://$GCS_BUCKET/dataproc --tag gcr.io/${{ secrets.GCP_PROJECT }}/dataproc-astra-job:latest

    - name: Push Docker Image to Google Container Registry
      run: |
        gcloud auth configure-docker
        docker push gcr.io/${{ secrets.GCP_PROJECT }}/dataproc-astra-job:latest

    - name: Submit Dataproc Job
      env:
        GCS_BUCKET: ${{ secrets.GCS_BUCKET }}
        GCS_OUTPUT_PATH: ${{ secrets.GCS_OUTPUT_PATH }}
      run: |
        gcloud dataproc batches submit pyspark gs://$GCS_BUCKET/dataproc/jobs/dataproc_astra_job.py \
          --region us-central1 \
          --deps-bucket gs://$GCS_BUCKET \
          --jars gs://$GCS_BUCKET/secure-connect-rc-pai-test.zip \
          --properties spark.jars.packages=com.datastax.spark:spark-cassandra-connector_2.12:3.1.0 \
          --container-image=gcr.io/${{ secrets.GCP_PROJECT }}/dataproc-astra-job:latest
